-- Tabela de Contratos
create table if not exists public.cap_manager_contratos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.cap_manager_clientes(id) on delete cascade not null,
  recorrente boolean default false,
  data_inicio date not null,
  data_fim date,
  valor numeric(10,2) not null default 0,
  ativo boolean default true,
  observacao text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Policy (se RLS estiver habilitado, ajustar conforme necessidade)
-- alter table public.cap_manager_contratos enable row level security;
-- create policy "Acesso total" on public.cap_manager_contratos for all using (true);
